language: bash
services: docker

script:
  - ./build
  # DOCKER_USER and $DOCKER_PASS are set in the Travis settings for the project.
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - \[\[ ( "$TRAVIS_PULL_REQUEST" == "false" ) && ( "$TRAVIS_BRANCH" == "master" || ${TRAVIS_BRANCH:0:1} == "v" ) ]] && docker push sqitch/sqitch

after_script:
  - docker images
